# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Example CI

# main branch에 Push될 때마다, main branch에 Pull Request될 때마다 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 이벤트가 발생할 때마다 Test 수행

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: 'npm'
    - run: npm ci
    - run: npm test
